name: Creative-1.21-R0.3
version: '${project.version}'
main: ru.rstudios.creative1.Creative_1
api-version: '1.21'
commands:
  games:
    aliases:
      - g
      - worlds
      - w
      - игры
      - п
      - пфьуы
      - ц
      - цщкдвы
  world:
    permission: creative.world
  plot:
    usage: /plot
    aliases:
      - здще
  join:
    usage: /join <id>
    aliases:
      - ощшт
  locale:
    usage: /locale
    aliases:
      - дщсфду
  build:
    usage: /build
    aliases:
      - игшдв
  play:
    usage: /play
    aliases:
      - здфн
      - кгт
      - run
  dev:
    usage: /dev
    aliases:
      - вум
  troubleshooter:
    usage: /troubleshooter
  vars:
    aliases:
      - мфкы