name: Creative-1.21-R0.3
version: '${project.version}'
main: ru.rstudios.creative1.Creative_1
api-version: '1.21'
commands:
  games:
    aliases:
      - g
      - worlds
      - w
      - игры
      - п
      - пфьуы
      - ц
      - цщкдвы
  world:
    permission: creative.world
  plot:
    usage: /plot
  join:
    usage: /join <id>
  locale:
    usage: /locale
  build:
    usage: /build
  play:
    usage: /play