name: Creative-1.21-R0.3
version: '${project.version}'
main: ru.rstudios.creative.CreativePlugin
api-version: '1.21'
authors: [ GromoverGets, tea_with_sugar ] # pawsashatoy легенда
depend:
  - LuckPerms
  - WorldEdit
  - ProtocolLib
softdepend:
  - PlaceholderAPI
commands:
  debuginfo:
    permission: creative.debug
  games:
    aliases:
      - g
      - worlds
      - w
      - игры
      - п
      - пфьуы
      - ц
      - цщкдвы
  world:
    permission: creative.world
  plot:
    usage: /plot
    aliases:
      - здще
      - world
      - цщкдв
  join:
    usage: /join <id>
    aliases:
      - ощшт
      - ad
      - фв
  locale:
    usage: /locale
    aliases:
      - дщсфду
      - lang
      - дфтп
  build:
    usage: /build
    aliases:
      - игшдв
  play:
    usage: /play
    aliases:
      - здфн
      - кгт
      - run
  dev:
    usage: /dev
    aliases:
      - вум
  troubleshooter:
    usage: /troubleshooter
  vars:
    aliases:
      - мфкы
  limit:
    permission: creative.setlimits
  like:
    aliases: дшлу
  query:
    permission: creative.query
  chat:
    aliases:
      - cc
      - сс
      - globalchat
      - global
      - пдщифд
      - пдщифдсрфе
      - срфе
      - чат
      - глобал
      - creativechat
      - скуфешмусрфе
  placeholders:
    aliases:
      - здфсурщдвукы
  diamondfire:
    aliases:
      - df